### ISSUE TITLE
Could not find gem 'jekyll (= 3.9.0) x64-mingw32' 新手提问

### ISSUE THREAD

**Issue by makerjackie** [hikerpig/foam-jekyll-template#1]
第一次搭建github page, 对jekyll还不大熟悉, 想请问

下载这个github仓库后, 执行命令
```
D:\workspace\docs\foam-jekyll-template-master
λ jekyll server --baseurl '.'
```
遇到如下错误
```log
....
Could not find gem 'jekyll (= 3.9.0) x64-mingw32' in any of the gem sources listed in your Gemfile. (Bundler::GemNotFound)
```

**Comment by makerjackie** [comment]
虽然不知道为什么, 但参照网上的说法

在Gemfile第一行加上
```
source 'https://rubygems.org'
```
然后在文件夹目录下依次执行
* `bundle install`
* `bundle exec jekyll serve`

然后就成功了😂

**Comment by makerjackie** [comment]
然后又在window下遇到中文乱码问题....(jekyll在window下自动采用GBK编码), 还得去找源码改... 太折腾了. 溜了溜了

**Comment by hikerpig** [comment]
@Jackiexiao 在 windows 下我还真是不了解了，我主要是有些笔记文件用坚果云同步，不想都用 git 追踪所以没选择官方的部署方案。 
现在都挺折腾的，我建议你实在要用 foam 这套又想本地编译部署的话（虽然有点疑问，难道不是找个linux云主机扔上去吗？），等一段时间用 gatsby 的 template，我看有些人从 gatsby roam 的模板改过来还挺好用的，能显示 graph view。

**Comment by makerjackie** [comment]
好咧, 感谢你的建议
