### ISSUE TITLE
部署到gitee的时候样式会丢失

### ISSUE THREAD

**Issue by makerjackie** [hikerpig/foam-jekyll-template#2]
复制了一下代码（非最新版本）放到gitee上方便国内访问， 不过出现了样式丢失（纯文本）的问题

网站：
http://jackiegeek.gitee.io/foam-jeklyy/
代码：
https://gitee.com/jackiegeek/foam-jeklyy

**Comment by hikerpig** [comment]
@Jackiexiao 
1. _config.yml 里 baseurl 要改为你自己的版本 `/foam-jeklyy`
2. 我最新的版本里把 _layouts/default.html 删掉了， `Gemfile` 里的 `jekyll-default-layout` 其实提供了 default layout，也考虑了样式相对路径的问题

样式丢失主要是 `style.css` 文件 404 了，你改完 1 以后再试试。 （同时也建议改下2，以免还有别的幺蛾子）

**Comment by makerjackie** [comment]
baseurl改好就可以了，后面还有个问题，github jekyll默认的主题primer有个地方gitee识别为语法错误

https://github.com/pages-themes/primer/blob/master/_layouts/default.html
里头把这行删掉
{% github_edit_link "Improve this page" %}.

**Comment by Jackiexiao** [comment]
jekyll-theme-primer  这个主题gitee不支持，部署的时候会遇到，好像是花括号的问题
```
部署失败
错误信息: Liquid syntax error (line 20): Unknown tag 'github_edit_link'
```

**Comment by hikerpig** [comment]
> baseurl改好就可以了，后面还有个问题，github jekyll默认的主题primer有个地方gitee识别为语法错误
> 
> https://github.com/pages-themes/primer/blob/master/_layouts/default.html
> 里头把这行删掉
> {% github_edit_link "Improve this page" %}.

这个依赖于 `jekyll-github-metadata` ，在 gitee 上可能是会有问题，晚些时候我再看看能不能通过加 Gem 解决

**Comment by makerjackie** [comment]
我换用mkdocs了，感觉支持的功能更多一些，可以见这里：https://github.com/Jackiexiao/foam-mkdocs-template

**Comment by hikerpig** [comment]
@Jackiexiao 看了一下观感很棒 👍 。不过我最近没时间折腾了... 想过段时间谁做出了带有 graphview 的模板直接换过去，一了百了
