### ISSUE TITLE
话说这个跟官方的foam-template区别在哪

### ISSUE THREAD

**Issue by makerjackie** [hikerpig/foam-jekyll-template#3]
好像是多了搜索和目录的功能

**Comment by hikerpig** [comment]
[foam-template](https://github.com/foambubble/foam-template) 的仓库最近 commit 是 3 个月前，比起官网版本有落后，我发现一些 foam 官网上有的功能并没有在该 template 里出现。
所以当时是拷贝了 foam 项目的 [docs 目录](https://github.com/foambubble/foam/tree/master/docs) 里的 _layouts 等，能跟官网发布的版本对上。
后来自己使用过程中根据自己需求加了 algolia 搜索以及 TOC 组件。

**Comment by makerjackie** [comment]
ok，感谢答复

**Comment by hikerpig** [comment]
总体来说我比较看好 VuePress/Gatsby/Gridsome 的方案。Jekyll 在 github 上支持很好，但是缺少好多知识库用途的关键组件，而本人 ruby 不是很熟。
目前来看很重要的 graph-view ，好像支持这个的模板还不多，蹲等官方新模板。
